### ISSUE TITLE
CLI not working

### ISSUE THREAD

**Issue by noraj** [mcollina/h2url#7]
I have this error when use h2url CLI:

```
$ ./node_modules/h2url/h2url.js https://127.0.0.1:3000
/usr/bin/env: ‘node --no-warnings’: No such file or directory
```

But `/usr/bin/env node --no-warnings` works if I write it in my shell.

**Comment by mcollina** [comment]
Which version of node are you using? which operating system are you on?
This is working fine on Node 8 or Node 9 on Mac OS X.

**Comment by noraj** [comment]
Node v9.2.0 on ArchLinux. I just tried on another machine and have the same behavior.

**Comment by noraj** [comment]
@mcollina Thx for the fix. I no longer have any error but I have an infinite loading instead and the result never shows up both with http or https.

```
$ ./node_modules/h2url/h2url.js https://github.com/
⠙ GET https://github.com/
$ ./node_modules/h2url/h2url.js http://www.tvcountdown.com
⠦ GET http://www.tvcountdown.com
```

**Comment by mcollina** [comment]
@noraj1337 are those http2-capable? have you tried with the embedded `server.js` file?

**Comment by noraj** [comment]
@mcollina My bad I didn't understand that h2url was http2 only.
